$("#kastroplayerlocaradio").kasradio({
userinterface: "big",
backgroundcolor: "transparent",
themecolor: "#e984ff", 
themefontcolor: "#ffffff", 
startvolume: "50", 
scroll: "true", 
useanalyzer: "real", 
analyzertype: "6", 
radioname: "MUSICALSENSATIONSRADIO",
usecover: "true",
radiocover: "https://i.imgur.com/TSc5ws2.gif",
streamtype: "zenoradio",
streamurl: "https://stream.zeno.fm/kd83asd0ra0uv.aac",
zenoid: "kd83asd0ra0uv",
usestreamcorsproxy: "true",
corsproxy: "",  
autoplay: "true",
songinformationinterval: "5000", 
});
