$("#kastroplayerlocaradio").kasradio({
userinterface: "big",
backgroundcolor: "transparent",
themecolor: "#266858", 
themefontcolor: "#ffffff", 
startvolume: "50", 
scroll: "true", 
useanalyzer: "real", 
analyzertype: "6", 
radioname: "ZonaLocaRadio",
usecover: "true",
radiocover: "https://i.imgur.com/TSc5ws2.gif",
streamtype: "zenoradio",
streamurl: "https://stream.zeno.fm/m61y2bgtvmzuv.aac",
zenoid: "m61y2bgtvmzuv",
usestreamcorsproxy: "true",
corsproxy: "",  
autoplay: "true",
songinformationinterval: "5000", 
});
